eureka:
    instance:
        client:
            serviceUrl:
                defaultZone: http://localhost:8761/eureka/
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 9191
spring:
    cloud:
        gateway:
            routes:
            -   id: microservice-1
                predicates:
                - Path=/microservice1/**
                uri: http://localhost:8001
            -   id: microservice-2
                predicates:
                - Path=/microservice2/**
                uri: http://localhost:8002
